### ISSUE TITLE
Incorrect records returned for reverse record lookup

### ISSUE THREAD

**Issue by ylukem** [wealdtech/go-ens#12]
I'm seeing the same ENS name have multiple addresses respond to its reverse record. I've attached a demo program:

```go
package main

import (
	"fmt"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	ens "github.com/wealdtech/go-ens/v3"
)

func main() {
	client, err := ethclient.Dial("https://mainnet.infura.io/v3/")
	if err != nil {
		panic(err)
	}

	start := common.HexToAddress("0xb9354777fd3019df43fa36a85e76ee3fe2f8bc35")
	reverse, err := ens.ReverseResolve(client, start)
	if err != nil {
		panic(err)
	}
	if reverse == "" {
		fmt.Printf("%s has no reverse lookup\n", start.Hex())
	} else {
		fmt.Printf("Name of %s is %s\n", start.Hex(), reverse)
	}

	confirm := common.HexToAddress("0x6924686B3DCD04Ae8ef91a3fEccC262d020F519D")
	reverse, err = ens.ReverseResolve(client, confirm)
	if err != nil {
		panic(err)
	}
	if reverse == "" {
		fmt.Printf("%s has no reverse lookup\n", confirm.Hex())
	} else {
		fmt.Printf("Name of %s is %s\n", confirm.Hex(), reverse)
	}

	// Resolve a name to an address
	domain := "itzler.eth"
	address, err := ens.Resolve(client, domain)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Address of %s is %s\n", domain, address.Hex())
}
```

When I run this program, I get the following output:
```bash
$ go run main.go
Name of 0xb9354777Fd3019DF43fA36a85E76eE3fE2F8bc35 is itzler.eth
Name of 0x6924686B3DCD04Ae8ef91a3fEccC262d020F519D is itzler.eth
Address of itzler.eth is 0x6924686B3DCD04Ae8ef91a3fEccC262d020F519D
```

Unless it's possible for the same reverse record to be associated with more than one address, I think there may be some bug here. Happy to help debug in any other way! I tried different RPC URLs from different providers and got the same results.

**Comment by mcdee** [comment]
It is indeed possible for multiple addresses to map to the same domain, in the same way that it is possible for multiple domains to map to the same address.  There is no concept of a single "reverse" record, it is a mapping from address=>name.

**Comment by tarrencev** [comment]
@mcdee i'm running into a similar scenario on my end. go-ens resolves `0x000000Be85f636189Fbe8f384A760A8C0779580B` to `pippen.eth` but it seems that neither etherscan nor ens.domains recognize that as a reverse resolution

**Comment by mcdee** [comment]
@tarrencev As per above, this is not an issue it is how ENS works.

**Comment by tarrencev** [comment]
ah ok. i guess they are considering only bidirectional resolution valid?
