### ISSUE TITLE
Feature Request: Support for non-IPFS content field values, including Skynet skylinks

### ISSUE THREAD

**Issue by dghelm** [wealdtech/go-ens#16]
Since ENS now officially supports various protocols for a domain's content record, I'd propose extending the functionality of `go-ens` to support additional protocols.

Specifically, I'm interested in `sia://` values as we work with a project using `go-ens` to better support Skynet.

Would love feedback on the idea and suggestions on where to start with a PR.

**Comment by mcdee** [comment]
Looks like `skynet-ns` is a registered multicodec already so you would need to look at updating contenthash.go with the relevant encoding and decoding steps.

**Comment by mcdee** [comment]
Added in #17
