### ISSUE TITLE
Support resolving multi chain address

### ISSUE THREAD

**Issue by hewigovens** [wealdtech/go-ens#2]
Hi @mcdee,

ENS now support multichain address https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2304.md, is it possible to support?

go-ens seems the only go libary listed in https://docs.ens.domains/dapp-developer-guide/ens-libraries#go

Thanks

**Comment by mcdee** [comment]
Support for multicoin has been added in version 3.0.9.  There is a simple name interface as per the README, and additional functions in the resolver to support getting and setting multicoin addresses.

I've also updated ethereal at version 2.0.11 to support getting and setting multicoin addresses so you can get and set them from the command line.

If you want to test this, I have deployed a multicoin-compatible ENS resolver at  on goerli at 0x2F8917BF6e5C8Fe258378eF266708F52925BbE35

Please let me know how you get on with this; thanks.

**Comment by hewigovens** [comment]
Thanks for the prompt support, will test it soon
