### ISSUE TITLE
Reverse resolution is returning invalid records

### ISSUE THREAD

**Issue by 0xfornax** [wealdtech/go-ens#29]
According to ENS [documentation](https://docs.ens.domains/dapp-developer-guide/resolving-names#reverse-resolution), the reverse record of an address is only valid if the forward resolution of that ENS name matches the address.

Current behavior:
The library is showing invalid ENS names as the result of reverse resolution calls.

Expected behavior:
The library should follow the ENS spec and validate if the reverse record is valid.

**Comment by mcdee** [comment]
That documentation says "accurate", not "valid".  It is valid for multiple addresses to point to the same ENS domains, as it is valid for multiple ENS domains to point to the same address.

The choice as to if to use an address that points to a given ENS domain which does not then itself resolve back to the address is up to the user, and not something that should be enforced in the library.
