### ISSUE TITLE
Can't hash valid ENS name

### ISSUE THREAD

**Issue by LuccaBitfly** [wealdtech/go-ens#34]
Consider "🚣‍♂️.eth", which is a valid & registered ENS domain. See https://app.ens.domains/🚣‍♂️.eth
In UTF-8 encoding, the 🚣‍♂️ (man rowing boat) emoji actually consists of 🚣 (person rowing boat) + `/u200d` ([zero width joiner](https://www.compart.com/en/unicode/U+200D)) + ♂️. For some reason, the `/u200d` symbol causes the name hash function to fail. E.g.:
```go
name := "🚣‍♂️" // 🚣\u200d♂️
nameHash, err := go_ens.NameHash(name)
if err != nil {
  // idna: invalid label \"🚣\\u200d♂\"
}
```

**Comment by Gordon420** [comment]
This been bothering me for years. Pls fix it

**Comment by mcdee** [comment]
Can you provide me with the namehash for this domain?

**Comment by LuccaBitfly** [comment]
The namehash should be `0x37f681401d88093779de0c910da1f9437759c2181f61b5dbc9e3ef0d9f192513` according to this ENS resolver: https://adraffy.github.io/ens-normalize.js/test/resolver.html#%F0%9F%9A%A3%E2%80%8D%E2%99%82.eth

**Comment by LuccaBitfly** [comment]
Thx :pray:
