### ISSUE TITLE
use btcd build failed

### ISSUE THREAD

**Issue by liujiefeng1011** [wealdtech/go-ens#44]
In my project, I want to import btcd@v0.24.0, but when I go build, it failed. I used command and it return:
go get github.com/btcsuite/btcd/txscript@v0.24.0
go: module github.com/btcsuite/btcd@v0.24.0 found, but does not contain package github.com/btcsuite/btcd/txscript

my go version is:
go version
go version go1.20.14 darwin/amd64

I clone the project from my collegue, it's strange that he can build the project successfully but i failed with
go build ./...
../../pkg/mod/github.com/btcsuite/btcd/btcutil@v1.1.5/address.go:17:2: no required module provides package github.com/btcsuite/btcd/chaincfg; to add it:
        go get github.com/btcsuite/btcd/chaincfg
../../pkg/mod/github.com/btcsuite/btcd/btcutil@v1.1.5/block.go:13:2: no required module provides package github.com/btcsuite/btcd/wire; to add it:
        go get github.com/btcsuite/btcd/wire

**Comment by mcdee** [comment]
Please raise an issue at https://github.com/btcsuite/btcd/issues as this is their repository.
